### ISSUE TITLE
Filters for the meeting list page

### ISSUE THREAD

**Issue by aaronarduino** [openwichita/public-meetings#17]

**Comment by Mearnest** [comment]
That would be very helpful. Possible ways to filter:

* Meeting type
     * council, boe, staff, etc.
     * Needs to be dropdown if it's going off machine names
* Title 
     * partial match?
* Date
    * Day, month, or time of day?
    * Calendar picker
    * Date Range
* Search
    * Type in and it matches on text in title, description, date
* Location
   * Could even be map or geo driven if we want to be fancy

**Comment by Mearnest** [comment]
We're able to use a query parameter to filter the meeting type by the first level (type not subtype). There is a route at the top of the meeting list that goes to a list of meetings you can select to filter the meeting events by. This is preliminary work for the UI which could consist of several components for filtering and searching meetings.
