### ISSUE TITLE
Determine data model for events

### ISSUE THREAD

**Issue by sethetter** [openwichita/public-meetings#3]
How do we store these? What does the model look like? What are the requirements, considering we want to display them on a website, and also serve them in an iCal feed?

**Comment by Mearnest** [comment]
Based on scraping and conversion to ical so far, the data looks like:

**type**:  meeting type, string (enum?)
**summary**: meeting title, string
**description**: brief general description, string
**location**: address, string
**date**: date & time, datetime
**agenda**: url to pdf or page, string
**email**: contact info, string

There can be additional fields, such as:
**agenda_final**: url to final version of the agenda pdf
**plat_drawings**: url to pdf of Subdivsion meeting map

**Comment by Mearnest** [comment]
JSON for a Regular Council Meeting would look like this:

{
"type": "council", 
"summary": "Regular Council Meeting", 
"description": "Provide policy direction for Wichita",
"location": "455 N Main, 1st Floor Board Room Wichita, KS 67202", 
"date": "2017-04-18T09:00:00", 
"agenda": "http://www.wichita.gov/Government/Council/Agendas/4-18-2017%20City%20Council%20Agenda%20Packet.pdf", 
"agenda_final": "http://www.wichita.gov/Government/Council/Agendas/4-18-2017%20Final%20City%20Council%20Agenda%20Packet.pdf"
 "email": "JCJohnson@wichita.gov;EGlock@wichita.gov;MLovely@wichita.gov;JHensley@wichita.gov;DLCityCouncilMembers@wichita.gov"
}

**Comment by sethetter** [comment]
@Mearnest is a "duration" or "end time" useful? Or possible?

**Comment by Mearnest** [comment]
Ah yes, I forgot about duration. Was just adding 2 hours to the start in the ical conversion. Duration should be added to the model. I didn't see where the Council or Subdivision meetings specified length of time, but I didn't dig very deeply.

**Comment by sethetter** [comment]
@Mearnest we definitely want to try and keep this generalized as much as possible too so the model will fit for non-council meetings as well. The idea is for this project to collect any sort of available public meeting for civic engagement, which is a pretty broad definition. Either way, a duration / end time would be great.

**Comment by Mearnest** [comment]
Right, the fields are based mostly on what I saw in ical file from an event I took off my calendar. Subdivision meeting has a plat drawing pdf in addition to the agenda pdf. I'm sure there will be other extra details, unless we don't want to allow additional fields.

**Comment by sethetter** [comment]
Definitely. I think what you have here is a perfect starting point, and we can add to it as the need arises. Thanks for this :)
