### ISSUE TITLE
Design of other pages

### ISSUE THREAD

**Issue by Mearnest** [openwichita/public-meetings#30]
The meetings page has been designed, and the front page has some layout, but the rest of the site is needing attention.

**Comment by sethetter** [comment]
Dropping a link to the design doc here for reference! https://paper.dropbox.com/doc/Open-Wichita-Public-Meetings-phUWrX8PJuUpfroQ56krE

**Comment by Mearnest** [comment]
@sethetter added the link to the Launch notes, so I'm closing this to reduce clutter.
