### ISSUE TITLE
Add iCal error

### ISSUE THREAD

**Issue by Mearnest** [openwichita/public-meetings#42]
When adding an individual ical meeting by clicking 'Add' button on the website, the following error occurs:

key :date not found in: %Meetings.MeetingType{__meta__:  

http://public-meetings.website/meetings/21/?format=ics

I'm wondering if I did not pull & update properly.

**Comment by doshitan** [comment]
Ah, no that's just broken. Changed some things last minute and guess I didn't test that. Will fix.
