### ISSUE TITLE
Improve display (html & css) of meeting list

### ISSUE THREAD

**Issue by sethetter** [openwichita/public-meetings#6]
HTML here -> `web/templates/meeting/index.html.eex`
CSS here -> `web/static/app.css`

Feel free to pull use bootstrap!

**Comment by aaronarduino** [comment]
I can take this on. Reading the Slack backlog, this might need to be a calendar? I found an css implementation of a calendar that I could use.

Although I'm not sure the current way of getting meetings on the page would suit a calendar. If we go the way of a calendar we would need to loop through all the dates in a month and on the days that have meetings add them to the html.

**Comment by sethetter** [comment]
@aaronarduino honestly I think a better first step is just a list view of the meetings. Not a table, but think a card or section for each event with the details laid out in just better-than-current typography.

I'm thinking [something like this](https://wichitaweso.me/), but doesn't have to be so well designed.

**Comment by aaronarduino** [comment]
Okay, that gives me a better direction. I'll see what I can do. :smile:

**Comment by aaronarduino** [comment]
I'm going to close this since pull request #16 was merged. Reopen if changes are needed.
