### ISSUE TITLE
Show list of meeting dates on Meeting Type show page

### ISSUE THREAD

**Issue by sethetter** [openwichita/public-meetings#8]
`web/templates/meeting_type/show.html.eex`
`web/controllers/meeting_type_controller.ex`

**Comment by Mearnest** [comment]
The meeting show template does this now, but it could live in meeting_type instead.. Anyway, the Meeting model demonstrates how to combine the meeting types and dates, and the show template demonstrates how to list them.

`web/templates/meeting/show.html.eex`
`web/controllers/meeting_controller.ex`
`web/models/meeting.ex`
