### ISSUE TITLE
Prototype / mockup data entry workflow

### ISSUE THREAD

**Issue by sethetter** [openwichita/public-meetings#9]
Designers? Anyone?

Could even just be some bootstrap HTML pages that we can turn into phoenix templates.

**Comment by sethetter** [comment]
Took some quick notes on what pages I think we need for now:

**Admin area for meeting management**

* "New Meeting" form
  * Basic form with meeting info fields
* List of "meeting types"
  * Show basic info, and "next date"
  * Link to "manage dates"
* "Manage Dates" page for existing meeting type
  * List of dates for the meeting
  * Basic JS-powered form for adding dates
  * [Wishlist] Recurring schedule and auto create?

**Public facing portion**

* All Meetings
  * All meeting dates, chronological
* Meeting page
  * Meeting info
  * List of dates

Thoughts anyone?

**Comment by Mearnest** [comment]
Recurring schedule and auto create would be really nice. That would more easily allow administrators to add a new meeting.

**Comment by sethetter** [comment]
Dropping a link to the design doc here for reference!

https://paper.dropbox.com/doc/Open-Wichita-Public-Meetings-phUWrX8PJuUpfroQ56krE
